In [24]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import linprog
from scipy.linalg import block_diag

# Games

- A is a payoff matrix.
- Player one chooses the column, player two chooses the row.
- $a_{ij}$ is the payoff for player 1
- $-a_{ij}$ is the payoff for player 2

In [4]:
A = np.array([
    [6, 8, 9, -15, -5, 2],
    [-16, 1, 3, -6, 23, -3],
    [-5, 12, -2, -4, 6, 1],
    [-16, -10, 11, -9, 3, 7]
])

A

array([[  6,   8,   9, -15,  -5,   2],
       [-16,   1,   3,  -6,  23,  -3],
       [ -5,  12,  -2,  -4,   6,   1],
       [-16, -10,  11,  -9,   3,   7]])

In [15]:
# represents uniform mixed strategys
p_1 = np.ones(A.shape[1]) / A.shape[1]
p_2 = np.ones(A.shape[0]) / A.shape[0]

p_2


array([0.25, 0.25, 0.25, 0.25])

In [11]:
# Expected payoffs for players one under this strategy conditioned on different plays for players 2.
A @ p_1

array([ 0.83333333,  0.33333333,  1.33333333, -2.33333333])

Expected Payoff for Player 1 $= (A p_1)^T p_2$
Expected Payoff for Player 2 $= -(A^T p_2)^T p_2$

In [22]:
e_1 = (A @ p_1) @ p_2
e_2 = -(A.T @ p_2) @ p_1

Modeling the constraints:

$p_1^T 1 = 1\\$
$p_2^T 1 = 1$

$x = [p_1^T, p_2^T]^T$

$A_{eq} = \begin{bmatrix}
    1 & ... & 1 & 0 &...& 0 \\
    0 &...& 0 & 1 & ... & 1\\
\end{bmatrix}$

$b_{eq} = \begin{bmatrix}
    1 \\
    1
\end{bmatrix}$

$A_{eq}x = b_{eq}$



In [28]:
A_eq = block_diag(np.ones_like(p_1), np.ones_like(p_2))
b_eq = np.ones(2)

res = linprog(c=np.zeros(A.shape[1] + A.shape[0]), A_ub=A, b_ub=np.zeros(A.shape[0]), A_eq=A_eq, b_eq=b_eq, bounds=(0, 1))
res

array([[1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.]])